# Build
FROM devopsfaith/krakend:latest AS build

COPY ./config/krakend.json /etc/krakend/krakend.json

RUN krakend check -c /etc/krakend/krakend.json


# Production
FROM devopsfaith/krakend:latest AS production

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

COPY ./config/krakend.json /etc/krakend/krakend.json

RUN krakend check -c /etc/krakend/krakend.json

COPY --from=build --chown=krakend /etc/krakend/krakend.json .